---
# cloud_controller_uri: api.vcap.me
service:
  name: mysql
  version: "5.1"
  description: 'MySQL database service'
  plans: ['free']
host: localhost
token: "0xdeadbeef"
log_level: DEBUG
redis_mbus: nats://localhost:4222
service_mbus: nats://localhost:4222
pid: /var/vcap/sys/run/mysql_service.pid
