---
# cloud_controller_uri: api.vcap.me
service:
  name: rabbit
  version: "2.4"
  description: 'RabbitMQ message queue'
  plans: ['free']
host: localhost
token: "0xdeadbeef"
log_level: DEBUG
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/rabbit_gateway.pid
