---
# cloud_controller_uri: api.vcap.me
service:
  name: mongodb
  version: "1.6"
  description: 'MongoDB NoSQL store'
  plans: ['free']
host: localhost
token: "0xdeadbeef"
service_mbus: nats://localhost:4222
mongodb_mbus: nats://localhost:4222
log_level: DEBUG
pid: /var/vcap/sys/run/mongodb_service.pid
